export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ISLOADING = "LOGIN_USER_ISLOADING";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";
export const USER_LOGOUT = "USER_LOGOUT";

export const POST_TYPES = {
  GET_POST_SUCCESS: "GET_STORE_SUCCESS",
  GET_POST_FAILED: "GET_STORE_FAILED",
  POST_LOADING_STATE: "STORE_LOADING_STATE"
};

export const PROFILE_INFO_TYPE = {
  GET_PROFILE_INFO_FAILED: "GET_PROFILE_INFO_FAILED",
  GET_PROFILE_INFO_SUCCESS: "GET_PROFILE_INFO_SUCCESS",
  GET_PROFILE_INFO_STATE: "GET_PROFILE_INFO_STATE",
  CHANGE_ONE_VALUE: "CHANGE_ONE_PROFILE_VALUE"
};

export const MY_POST = {
  FAILED: "MY_POST_FETCH_FAILED",
  SUCCESS: "MY_POST_FETCH_SUCCESS",
  LOADING: "MY_POST_LOADING_STATUS"
};

export const USER_PROFILE_INFO = {
  FAILED: "GET_USER_PROFILE_INFO_FAILED",
  SUCCESS: "GET_USER_PROFILE_INFO_SUCCESS",
  LOADING: "GET_USER_PROFILE_INFO_STATE"
};
